import 'dotenv/config';

export const env = {
  minimaxApiKey: process.env.MINIMAX_API_KEY ?? '',
  minimaxBaseUrl: process.env.MINIMAX_BASE_URL ?? 'https://api.minimax.chat/v1',
  minimaxModel: process.env.MINIMAX_MODEL ?? 'MiniMax-text-01',
  minimaxEmbeddingModel: process.env.MINIMAX_EMBEDDING_MODEL ?? 'embo-01',
  embeddingProvider: process.env.EMBEDDING_PROVIDER ?? 'minimax',
  embeddingBatchSize: Number(process.env.EMBEDDING_BATCH_SIZE ?? 8),
  openRouterApiKey: process.env.OPENROUTER_API_KEY ?? '',
  openRouterBaseUrl: process.env.OPENROUTER_BASE_URL ?? 'https://openrouter.ai/api/v1',
  openRouterEmbeddingModel: process.env.OPENROUTER_EMBEDDING_MODEL ?? 'openai/text-embedding-3-small',
  ollamaBaseUrl: process.env.OLLAMA_BASE_URL ?? 'http://127.0.0.1:11434',
  ollamaEmbeddingModel: process.env.OLLAMA_EMBEDDING_MODEL ?? 'qwen3-embedding:4b',
  // Keep in sync with PGVECTOR_DIMENSIONS (and any vector(...) migration).
  // Ollama qwen3-embedding:4b is native 2560; request/truncate to stay ≤2000 for HNSW.
  embeddingDimensions: Number(process.env.EMBEDDING_DIMENSIONS ?? process.env.PGVECTOR_DIMENSIONS ?? 2048),
  databaseUrl: process.env.DATABASE_URL ?? '',
  pgVectorDimensions: Number(process.env.PGVECTOR_DIMENSIONS ?? 2048),
  redisHost: process.env.REDIS_HOST ?? 'localhost',
  redisPort: Number(process.env.REDIS_PORT ?? 6379),
  qdrantUrl: process.env.QDRANT_URL ?? 'http://localhost:6333',
  qdrantApiKey: process.env.QDRANT_API_KEY ?? '',
  qdrantCollection: process.env.QDRANT_COLLECTION ?? 'security_events',
  dedupSimilarityThreshold: Number(process.env.DEDUP_SIMILARITY_THRESHOLD ?? 0.82),
  searchContextSize: process.env.SEARCH_CONTEXT_SIZE ?? 'medium',
  monitorLookbackHours: Number(process.env.MONITOR_LOOKBACK_HOURS ?? 6),
  rssFetchIntervalMinutes: Number(process.env.RSS_FETCH_INTERVAL_MINUTES ?? 30),
  httpExtractionConcurrency: Number(process.env.HTTP_EXTRACTION_CONCURRENCY ?? 10),
  playwrightExtractionConcurrency: Number(process.env.PLAYWRIGHT_EXTRACTION_CONCURRENCY ?? 2),
  playwrightExtractionTimeoutMs: Number(process.env.PLAYWRIGHT_EXTRACTION_TIMEOUT_MS ?? 15000),
  playwrightMinTextLength: Number(process.env.PLAYWRIGHT_MIN_TEXT_LENGTH ?? 250),
  llmConcurrency: Number(process.env.LLM_CONCURRENCY ?? 3),
  llmTimeoutMs: Number(process.env.LLM_TIMEOUT_MS ?? 60000),
  alertSuppressionHours: Number(process.env.ALERT_SUPPRESSION_HOURS ?? 6),
  earlyWarningWindowHours: Number(process.env.EARLY_WARNING_WINDOW_HOURS ?? 24),
  alertLatencySloHours: Number(process.env.ALERT_LATENCY_SLO_HOURS ?? 2),
  minAlertConfidence: Number(process.env.MIN_ALERT_CONFIDENCE ?? 0.75),
};
