import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { z } from 'zod';
import type { VendorProduct } from '../types/domain.js';

/**
 * The monitored vendor/product inventory lives in config/monitored-vendors.json
 * so it can be edited without touching code — including from the eval review
 * UI's Inventory tab (paste JSON, e.g. generated by an LLM).
 *
 * Proof-of-concept scope: 3 vendor products (CyberArk PAS, Zscaler ZIA,
 * Microsoft Windows Server/Exchange/Entra). Expand after the evaluation gate
 * is trustworthy at this scope.
 *
 * Note: long-running processes (scheduler, worker) read this at startup;
 * `reloadMonitoredVendors()` refreshes in-process consumers. Run
 * `npm run seed:vendors` to sync the database copy used by other stages.
 */
export const MONITORED_VENDORS_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  '../../config/monitored-vendors.json'
);

export const VendorProductSchema = z.object({
  id: z
    .string()
    .min(1)
    .optional(),
  vendor: z.string().trim().min(1),
  product: z.string().trim().min(1),
  aliases: z.array(z.string().trim().min(1)).default([]),
  criticality: z.enum(['critical', 'high', 'medium', 'low']),
  inProduction: z.boolean().default(true),
});

export const VendorInventorySchema = z.array(VendorProductSchema).min(1);

export function parseVendorInventory(input: unknown): VendorProduct[] {
  const parsed = VendorInventorySchema.parse(input);
  const seen = new Map<string, number>();
  return parsed.map((item, index) => {
    const id = item.id ?? deriveVendorProductId(item.vendor, item.product);
    const duplicate = seen.get(id);
    if (duplicate !== undefined) {
      throw new Error(`Duplicate vendor product id "${id}" (entries ${duplicate + 1} and ${index + 1}). Vendor+product pairs must be unique.`);
    }
    seen.set(id, index);
    return { ...item, id, aliases: dedupe(item.aliases) };
  });
}

export function deriveVendorProductId(vendor: string, product: string): string {
  const slug = `${vendor} ${product}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
  return `vp_${slug}`;
}

export function loadMonitoredVendors(path: string = MONITORED_VENDORS_PATH): VendorProduct[] {
  let raw: string;
  try {
    raw = readFileSync(path, 'utf8');
  } catch (error) {
    throw new Error(`Cannot read monitored vendor inventory at ${path}: ${(error as Error).message}`);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new Error(`Invalid JSON in monitored vendor inventory at ${path}: ${(error as Error).message}`);
  }
  return parseVendorInventory(parsed);
}

/**
 * Live inventory. Consumers hold a reference to this array; save/reload mutate
 * it in place so the whole process (filter, entity extractor, eval report)
 * sees updates without a restart.
 */
export const monitoredVendors: VendorProduct[] = loadMonitoredVendors();

export function reloadMonitoredVendors(path: string = MONITORED_VENDORS_PATH): VendorProduct[] {
  const fresh = loadMonitoredVendors(path);
  monitoredVendors.length = 0;
  monitoredVendors.push(...fresh);
  return monitoredVendors;
}

/** Validates, persists, and hot-reloads the inventory. Returns the normalized list. */
export function saveMonitoredVendors(input: unknown, path: string = MONITORED_VENDORS_PATH): VendorProduct[] {
  const normalized = parseVendorInventory(input);
  writeFileSync(path, `${JSON.stringify(normalized, null, 2)}\n`);
  if (path === MONITORED_VENDORS_PATH) {
    monitoredVendors.length = 0;
    monitoredVendors.push(...normalized);
  }
  return normalized;
}

function dedupe(values: string[]): string[] {
  return Array.from(new Set(values));
}
